Update IdentifyingWebElements file as latest change
These are the modification that are done. Since the course had made there are many changes made in the Web page
First change on 
Driver.Manage().Window.Maximize();
Purpose to avoid element not found 
Details 
Message: 
    Test method ElementInteractions.IdentifyingWebElements.SeleniumElementLocationExam threw exception: 
    OpenQA.Selenium.ElementClickInterceptedException: element click intercepted: Element <input type="radio" name="gender" value="male"> is not clickable at point (112, 609). Other element would receive the click: <div class="nc_wrapper swp_floating_horizontal_wrapper bottom" style="background-color: rgb(255, 255, 255); visibility: visible;">...</div>
      (Session info: chrome=81.0.4044.138)
  Stack Trace: 
    RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
    RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
    RemoteWebElement.Click()
    IdentifyingWebElements.SeleniumElementLocationExam() line 137

Second change 
Driver.FindElement(By.XPath("//*[@class='et_pb_tab et_pb_tab_1 clearfix et-pb-active-slide']")).Text
You have many CSS modifications after 2017, this is not reflecting on the source code, I am getting the following error
 
  Message: 
    Test method ElementInteractions.IdentifyingWebElements.SeleniumElementLocationExam threw exception: 
    OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@class='et_pb_tab clearfix et_pb_tab_1 et-pb-active-slide']"}
      (Session info: chrome=81.0.4044.138)
  Stack Trace: 
    RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
    RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    RemoteWebDriver.FindElement(String mechanism, String value)
    RemoteWebDriver.FindElementByXPath(String xpath)
    <>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
    By.FindElement(ISearchContext context)
    RemoteWebDriver.FindElement(By by)
    IdentifyingWebElements.SeleniumElementLocationExam() line 147



Third change to scroll the window till the end in downward direction 
// scrolling through the window till the SEction "Highlight me" is shown
            IJavaScriptExecutor JavaScriptExecutor = Driver as IJavaScriptExecutor;
            JavaScriptExecutor.ExecuteScript("window.scrollTo(0, document.body.scrollHeight)");
 To avoid the following error when the Section "Highlight me" is not shown 
 Message: 
    Test method ElementInteractions.IdentifyingWebElements.SeleniumElementLocationExam threw exception: 
    OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@class='et_pb_tab clearfix et_pb_tab_1 et-pb-active-slide']"}
      (Session info: chrome=81.0.4044.138)
  Stack Trace: 
    RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
    RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    RemoteWebDriver.FindElement(String mechanism, String value)
    RemoteWebDriver.FindElementByXPath(String xpath)
    <>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
    By.FindElement(ISearchContext context)
    RemoteWebDriver.FindElement(By by)
    IdentifyingWebElements.SeleniumElementLocationExam() line 147


line 
            HighlightElementUsingJavaScript(By.XPath("et_pb_column et_pb_column_1_3  et_pb_column_10 et_pb_css_mix_blend_mode_passthrough"));
gives error as follows

OpenQA.Selenium.InvalidSelectorException
  HResult=0x80131500
  Message=invalid selector: Unable to locate an element with the xpath expression et_pb_column et_pb_column_1_3  et_pb_column_10 et_pb_css_mix_blend_mode_passthrough because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string 'et_pb_column et_pb_column_1_3  et_pb_column_10 et_pb_css_mix_blend_mode_passthrough' is not a valid XPath expression.
  (Session info: chrome=81.0.4044.138)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
 You have mentioned clearly that the By.ClassName must not used that gives us error. The code is misplaced.